version: '3.9'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: servicehub_postgres
    environment:
      POSTGRES_DB: servicehub
      POSTGRES_USER: servicehub
      POSTGRES_PASSWORD: servicehub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U servicehub"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: servicehub_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Django Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: servicehub_backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py createsuperuser --noinput --username admin --email admin@servicehub.com || true &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 4"
    environment:
      DEBUG: "False"
      SECRET_KEY: "your-secret-key-change-in-production"
      ALLOWED_HOSTS: "localhost,127.0.0.1,0.0.0.0,backend"
      DB_ENGINE: "django.db.backends.postgresql"
      DB_NAME: "servicehub"
      DB_USER: "servicehub"
      DB_PASSWORD: "servicehub"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      REDIS_URL: "redis://redis:6379/0"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:5173"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/schema/"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Celery Worker
  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: servicehub_celery
    command: celery -A config worker -l info
    environment:
      DEBUG: "False"
      SECRET_KEY: "your-secret-key-change-in-production"
      ALLOWED_HOSTS: "localhost,127.0.0.1,0.0.0.0,backend"
      DB_ENGINE: "django.db.backends.postgresql"
      DB_NAME: "servicehub"
      DB_USER: "servicehub"
      DB_PASSWORD: "servicehub"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      REDIS_URL: "redis://redis:6379/0"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    depends_on:
      - postgres
      - redis
      - backend
    volumes:
      - ./backend:/app

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: servicehub_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/staticfiles:/app/staticfiles:ro
      - ./backend/media:/app/media:ro
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/api/schema/"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: servicehub_network

